### ISSUE TITLE
Bing Chat Enterprise for faculty

### ISSUE THREAD

**Issue by skyblaster** [rbalsleyMSFT/IntuneScripts#2]
With [this announcement](https://educationblog.microsoft.com/en-us/2023/08/announcing-bing-chat-enterprise-for-faculty-and-search-progress), I of course went to enable it right away.

I think it would be a great idea to separate the policies for students vs. faculty, as in the case above, SafeSearch being set to strict, causes Bing chat to be blocked.

![image](https://github.com/rbalsleyMSFT/IntuneScripts/assets/1776037/7f6713fc-9ebd-414d-ae96-073ee857971f)

**Comment by rbalsleyMSFT** [comment]
Good idea. Strict safesearch should be for students only.
