### ISSUE TITLE
Please review User vs Device settings for Deny Administrative Apps

### ISSUE THREAD

**Issue by skyblaster** [rbalsleyMSFT/IntuneScripts#3]
It's possible I did something wrong, but when enabling the [Deny Administrative Apps](https://github.com/rbalsleyMSFT/IntuneScripts/tree/main/ConfigurationProfileSettings#deny-administrative-apps) settings as per the instructions here, and verifying that the XML exists within `C:\Windows\System32\AppLocker\MDM\...\IntuneEdu\EXE\Policy`, the policy does not take effect.

Following [Rudy's blog post](https://call4cloud.nl/2020/06/blocking-administrative-apps-like-the-command-prompt-in-intune/) and using the Intune for Education portal to enable this policy, the default setting applies to All Devices, not to users. This worked, whereas applying to a Student user group earlier did not.

The resulting XML in `C:\Windows\System32\AppLocker\MDM\...\IntuneEdu\EXE\Policy` was also formatted slightly differently, even though I downloaded as raw from GitHub and made sure to upload to Intune as "String (XML file)"

**Comment by rbalsleyMSFT** [comment]
That's weird. I wonder if github is maybe breaking the formatting of the XML file (there are some weird characters in the productname tags). 

Can you try copy and pasting the below into a String data type in your custom OMA-URI (no need to save as an XML). Ultimately, whatever Intune for Education creates, or the txt file that Rudy has, or the below, whatever works is fine. In I4E though, it will target to a device group, but you can change the group it's targeted to in the full Intune console (change to a user group). 

`<RuleCollection Type="Exe" EnforcementMode="NotConfigured">
        <FilePathRule Id="fd686d83-a829-4351-8ff4-27c7de5755d2" Name="(Default Rule) All files" Description="Allows members of the local Administrators group to run all applications." UserOrGroupSid="S-1-5-32-544" Action="Allow">
          <Conditions>
            <FilePathCondition Path="*" />
          </Conditions>
        </FilePathRule>
        <FilePathRule Id="ce9d9fd5-d765-48df-b87b-e1bafd5653ed" Name="All files" Description="Allows members of the Everyone group to run applications that are located in any folder." UserOrGroupSid="S-1-1-0" Action="Allow">
          <Conditions>
            <FilePathCondition Path="*" />
          </Conditions>
                        <Exceptions>
                    <FilePublisherCondition PublisherName="O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US" ProductName="MICROSOFTÂ® WINDOWSÂ® OPERATING SYSTEM" BinaryName="CMD.EXE">
          <BinaryVersionRange LowSection="*" HighSection="*" />
        </FilePublisherCondition>
                    <FilePublisherCondition PublisherName="O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US" ProductName="MICROSOFTÂ® WINDOWSÂ® OPERATING SYSTEM" BinaryName="POWERSHELL.EXE">
          <BinaryVersionRange LowSection="*" HighSection="*" />
        </FilePublisherCondition>
        <FilePublisherCondition PublisherName="O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US" ProductName="MICROSOFTÂ® WINDOWSÂ® OPERATING SYSTEM" BinaryName="POWERSHELL_ISE.EXE">
          <BinaryVersionRange LowSection="*" HighSection="*" />
        </FilePublisherCondition>
                    <FilePublisherCondition PublisherName="O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US" ProductName="MICROSOFTÂ® WINDOWSÂ® OPERATING SYSTEM" BinaryName="REGEDIT.EXE">
          <BinaryVersionRange LowSection="*" HighSection="*" />
        </FilePublisherCondition>
        <FilePublisherCondition PublisherName="O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US" ProductName="MICROSOFTÂ® WINDOWSÂ® OPERATING SYSTEM" BinaryName="REG.EXE">
          <BinaryVersionRange LowSection="*" HighSection="*" />
        </FilePublisherCondition>
                </Exceptions>
        </FilePathRule>
     </RuleCollection>`

**Comment by skyblaster** [comment]
I tried as a string and same result.

Fun fact. The policy file ending up in `C:\Windows\System32\AppLocker\MDM\...\IntuneEdu\EXE\` is processed, therefore changing from "String (XML)" to "String" does have an effect on this processing.

My best guess at the moment is that the original XML generated by I4E has extra line feeds or carriage returns that are not being copied somewhere in the process. I would need to download the original via Graph to confirm.

For the title of this issue, I can at least confirm that the I4E generated policy does work with user groups. It is not device specific setting.

**Comment by rbalsleyMSFT** [comment]
It appears that when I4E creates the policy, it does so as a String(XML) file. When the full Intune UI shows the custom XML, it displays this funny A character before the registered trademark symbol after Microsoft and Windows. I created my own Applocker file via GP and didn't have these characters and uploaded that as a custom OMA-URI and it worked fine. So the export out of Intune is what's breaking this. I'll re-upload my clean file and this should be good. 

![image](https://github.com/rbalsleyMSFT/IntuneScripts/assets/53497092/37e5e7c6-2090-43e9-84a8-aee10e24654e)
