### ISSUE TITLE
Edge Toolbar - Installed Extensions default to show instead of hidden

### ISSUE THREAD

**Issue by skyblaster** [rbalsleyMSFT/IntuneScripts#4]
As per the following guide, the default toolbar_state is supposed to be `default_hidden` for all extensions in Edge 103 and above:
https://learn.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-ref-guide

For the current Edge 115, in my testing, this appears to default to `default_shown` instead.

Is there a CSP or OMA-URI to change this behavior? Thanks!

**Comment by rbalsleyMSFT** [comment]
There wouldn't be a CSP as the Edge settings in the Settings Catalog are derived from ADMX imports that the Intune team does to get the settings from Edge. 

It's possible that this is a bug. I'll need to test and look into it. Is this causing issues?

**Comment by skyblaster** [comment]
Thanks. I suppose I could handle this with a custom ADMX import.

I'm enabling a couple extensions via `Allow specific extensions to be installed` and `Control which extensions are installed silently`. So, the only issue is like you mentioned in [PR #1](https://github.com/rbalsleyMSFT/IntuneScripts/pull/1#discussion_r1302304862), these icons take up precious real-estate on the toolbar.

**Comment by rbalsleyMSFT** [comment]
Closing the issue as it's not related to default settings. Still unsure why it doesn't work as expected.
