### ISSUE TITLE
Configuration Profile Settings for other device types

### ISSUE THREAD

**Issue by skyblaster** [rbalsleyMSFT/IntuneScripts#6]
The ConfigurationProfileSettings section of this repo is such an excellent resource. Thank you so much for all the work you've put into it!
I'm just curious if you have any plans for adding other device types, specifically iOS/iPadOS and macOS?

Thanks again!

**Comment by rbalsleyMSFT** [comment]
Sorry for such a late response on this issue. Somehow I didn't get an email about it, or just missed it.

I don't have any plans for Apple devices. I know there's a MacAdmins community https://github.com/microsoft/shell-intune-samples/wiki/Microsoft-Mac-Admins-Community, but it's not built for EDU specifically.
